name: Go

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: checkout
        uses: actions/checkout@v3

      - name: Test
        run: go test -v ./...
